// Generated by worker/test/write-protocol-class-from-common-bridge.mjs.
// Do not edit by hand.

#include "ir_Mirage.h"

namespace {

bool generateClassFromCommonJson(const char *className,
                                 const stdAc::state_t &common,
                                 uint16_t repeat,
                                 std::string &result) {
  if (className == nullptr || *className == '\0') {
    result = errorJson("className is required");
    return true;
  }
  if (!std::strcmp(className, "IRMirageAc")) {
    IRMirageAc ac(0);
    ac.fromCommon(common);
    timingList.clear();
    ac.send(repeat);
    const stdAc::state_t roundTrip = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classFromCommon\",";
    out << "\"className\":\"IRMirageAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, roundTrip, "", "IRMirageAc");
    out << ",";
    appendState(out, ac.getRaw(), kMirageStateLength);
    out << ",";
    appendTimingList(out, "raw");
    out << ",\"frequency\":38000";
    out << "}";
    result = out.str();
    return true;
  }
  return false;
}

}  // namespace
