// Generated by worker/test/write-protocol-class-common-bridge.mjs.
// Do not edit by hand.

#include "ir_Airton.h"
#include "ir_Airwell.h"
#include "ir_Amcor.h"
#include "ir_Argo.h"
#include "ir_Bosch.h"
#include "ir_Carrier.h"
#include "ir_Coolix.h"
#include "ir_Corona.h"
#include "ir_Daikin.h"
#include "ir_Delonghi.h"
#include "ir_Ecoclim.h"
#include "ir_Electra.h"
#include "ir_Eurom.h"
#include "ir_Fujitsu.h"
#include "ir_Goodweather.h"
#include "ir_Gree.h"
#include "ir_Haier.h"
#include "ir_Hitachi.h"
#include "ir_Kelon.h"
#include "ir_Kelvinator.h"
#include "ir_LG.h"
#include "ir_Midea.h"
#include "ir_Mirage.h"
#include "ir_Mitsubishi.h"
#include "ir_MitsubishiHeavy.h"
#include "ir_Neoclima.h"
#include "ir_Panasonic.h"
#include "ir_Rhoss.h"
#include "ir_Samsung.h"
#include "ir_Sanyo.h"
#include "ir_Sharp.h"
#include "ir_Tcl.h"
#include "ir_Technibel.h"
#include "ir_Teco.h"
#include "ir_Toshiba.h"
#include "ir_Transcold.h"
#include "ir_Trotec.h"
#include "ir_Truma.h"
#include "ir_Vestel.h"
#include "ir_Voltas.h"
#include "ir_Whirlpool.h"
#include "ir_York.h"

namespace {

bool generateClassCommonJson(const char *className,
                             const std::vector<uint8_t> &state,
                             uint64_t rawValue,
                             std::string &result) {
  if (className == nullptr || *className == '\0') {
    result = errorJson("className is required");
    return true;
  }
  if (!std::strcmp(className, "IRAirtonAc")) {
    IRAirtonAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRAirtonAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRAirtonAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRAirwellAc")) {
    IRAirwellAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRAirwellAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRAirwellAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRAmcorAc")) {
    IRAmcorAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRAmcorAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRAmcorAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kAmcorStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRArgoAC")) {
    IRArgoAC ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRArgoAC\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRArgoAC");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(ac.getRawByteLength()) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRArgoAC_WREM3")) {
    IRArgoAC_WREM3 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRArgoAC_WREM3\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRArgoAC_WREM3");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(ac.getRawByteLength()) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRBosch144AC")) {
    IRBosch144AC ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRBosch144AC\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRBosch144AC");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kBosch144StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRCarrierAc64")) {
    IRCarrierAc64 ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRCarrierAc64\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRCarrierAc64");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRCoolixAC")) {
    IRCoolixAC ac(0);
    ac.setRaw(static_cast<uint32_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRCoolixAC\",";
    out << "\"rawType\":\"uint32\",";
    appendCommonAcObject(out, common, "", "IRCoolixAC");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRCoronaAc")) {
    IRCoronaAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRCoronaAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRCoronaAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kCoronaAcStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDaikin312")) {
    IRDaikin312 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDaikin312\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRDaikin312");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kDaikin312StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDaikinESP")) {
    IRDaikinESP ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDaikinESP\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRDaikinESP");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kDaikinStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDaikin2")) {
    IRDaikin2 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDaikin2\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRDaikin2");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kDaikin2StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDaikin216")) {
    IRDaikin216 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDaikin216\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRDaikin216");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kDaikin216StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDaikin160")) {
    IRDaikin160 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDaikin160\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRDaikin160");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kDaikin160StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDaikin176")) {
    IRDaikin176 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDaikin176\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRDaikin176");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kDaikin176StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDaikin128")) {
    IRDaikin128 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDaikin128\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRDaikin128");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kDaikin128StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDaikin152")) {
    IRDaikin152 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDaikin152\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRDaikin152");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kDaikin152StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDaikin64")) {
    IRDaikin64 ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDaikin64\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRDaikin64");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRDelonghiAc")) {
    IRDelonghiAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRDelonghiAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRDelonghiAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IREcoclimAc")) {
    IREcoclimAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IREcoclimAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IREcoclimAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRElectraAc")) {
    IRElectraAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRElectraAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRElectraAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kElectraAcStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IREuromAc")) {
    IREuromAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IREuromAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IREuromAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kEuromStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRFujitsuAC")) {
    IRFujitsuAC ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRFujitsuAC\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRFujitsuAC");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(ac.getStateLength()) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRGoodweatherAc")) {
    IRGoodweatherAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRGoodweatherAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRGoodweatherAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRGreeAC")) {
    IRGreeAC ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRGreeAC\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRGreeAC");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kGreeStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHaierAC")) {
    IRHaierAC ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHaierAC\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHaierAC");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHaierACStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHaierAC176")) {
    IRHaierAC176 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHaierAC176\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHaierAC176");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHaierAC176StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHaierACYRW02")) {
    IRHaierACYRW02 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHaierACYRW02\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHaierACYRW02");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHaierACYRW02StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHaierAC160")) {
    IRHaierAC160 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHaierAC160\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHaierAC160");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHaierAC160StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc")) {
    IRHitachiAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHitachiAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHitachiAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHitachiAcStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc1")) {
    IRHitachiAc1 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHitachiAc1\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHitachiAc1");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHitachiAc1StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc424")) {
    IRHitachiAc424 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHitachiAc424\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHitachiAc424");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHitachiAc424StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc344")) {
    IRHitachiAc344 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHitachiAc344\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHitachiAc344");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHitachiAc344StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc264")) {
    IRHitachiAc264 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHitachiAc264\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHitachiAc264");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHitachiAc264StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc296")) {
    IRHitachiAc296 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRHitachiAc296\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRHitachiAc296");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kHitachiAc296StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRKelonAc")) {
    IRKelonAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRKelonAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRKelonAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRKelon168Ac")) {
    IRKelon168Ac ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRKelon168Ac\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRKelon168Ac");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kKelon168StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRKelvinatorAC")) {
    IRKelvinatorAC ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRKelvinatorAC\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRKelvinatorAC");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kKelvinatorStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRLgAc")) {
    IRLgAc ac(0);
    ac.setRaw(static_cast<uint32_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRLgAc\",";
    out << "\"rawType\":\"uint32\",";
    appendCommonAcObject(out, common, "", "IRLgAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRMideaAC")) {
    IRMideaAC ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRMideaAC\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRMideaAC");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRMirageAc")) {
    IRMirageAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRMirageAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRMirageAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kMirageStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishiAC")) {
    IRMitsubishiAC ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRMitsubishiAC\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRMitsubishiAC");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kMitsubishiACStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishi136")) {
    IRMitsubishi136 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRMitsubishi136\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRMitsubishi136");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kMitsubishi136StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishi112")) {
    IRMitsubishi112 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRMitsubishi112\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRMitsubishi112");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kMitsubishi112StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishiHeavy152Ac")) {
    IRMitsubishiHeavy152Ac ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRMitsubishiHeavy152Ac\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRMitsubishiHeavy152Ac");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kMitsubishiHeavy152StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishiHeavy88Ac")) {
    IRMitsubishiHeavy88Ac ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRMitsubishiHeavy88Ac\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRMitsubishiHeavy88Ac");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kMitsubishiHeavy88StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRNeoclimaAc")) {
    IRNeoclimaAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRNeoclimaAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRNeoclimaAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kNeoclimaStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRPanasonicAc")) {
    IRPanasonicAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRPanasonicAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRPanasonicAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kPanasonicAcStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRPanasonicAc32")) {
    IRPanasonicAc32 ac(0);
    ac.setRaw(static_cast<uint32_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRPanasonicAc32\",";
    out << "\"rawType\":\"uint32\",";
    appendCommonAcObject(out, common, "", "IRPanasonicAc32");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRRhossAc")) {
    IRRhossAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRRhossAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRRhossAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kRhossStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRSamsungAc")) {
    IRSamsungAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRSamsungAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRSamsungAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kSamsungAcStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRSanyoAc")) {
    IRSanyoAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRSanyoAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRSanyoAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kSanyoAcStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRSanyoAc88")) {
    IRSanyoAc88 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRSanyoAc88\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRSanyoAc88");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kSanyoAc88StateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRSharpAc")) {
    IRSharpAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRSharpAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRSharpAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kSharpAcStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRTcl112Ac")) {
    IRTcl112Ac ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRTcl112Ac\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRTcl112Ac");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kTcl112AcStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRTechnibelAc")) {
    IRTechnibelAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRTechnibelAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRTechnibelAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRTecoAc")) {
    IRTecoAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRTecoAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRTecoAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRToshibaAC")) {
    IRToshibaAC ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRToshibaAC\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRToshibaAC");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(ac.getStateLength()) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRTranscoldAc")) {
    IRTranscoldAc ac(0);
    ac.setRaw(static_cast<uint32_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRTranscoldAc\",";
    out << "\"rawType\":\"uint32\",";
    appendCommonAcObject(out, common, "", "IRTranscoldAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRTrotecESP")) {
    IRTrotecESP ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRTrotecESP\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRTrotecESP");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kTrotecStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRTrotec3550")) {
    IRTrotec3550 ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRTrotec3550\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRTrotec3550");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kTrotecStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRTrumaAc")) {
    IRTrumaAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRTrumaAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRTrumaAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRVestelAc")) {
    IRVestelAc ac(0);
    ac.setRaw(static_cast<uint64_t>(rawValue));
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRVestelAc\",";
    out << "\"rawType\":\"uint64\",";
    appendCommonAcObject(out, common, "", "IRVestelAc");
    out << ",";
    out << "\"value\":\"" << static_cast<unsigned long long>(ac.getRaw()) << "\",";
  out << "\"valueHex\":\"" << hex64(static_cast<uint64_t>(ac.getRaw())) << "\"";
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRVoltas")) {
    IRVoltas ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRVoltas\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRVoltas");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kVoltasStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRWhirlpoolAc")) {
    IRWhirlpoolAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRWhirlpoolAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRWhirlpoolAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kWhirlpoolAcStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  if (!std::strcmp(className, "IRYorkAc")) {
    IRYorkAc ac(0);
    if (!state.empty()) {
      ac.setRaw(state.data(), state.size());
    }
    const stdAc::state_t common = ac.toCommon();
    std::ostringstream out;
    out << "{\"kind\":\"classCommon\",";
    out << "\"className\":\"IRYorkAc\",";
    out << "\"rawType\":\"bytes\",";
    appendCommonAcObject(out, common, "", "IRYorkAc");
    out << ",";
    appendState(out, ac.getRaw(), state.empty() ? static_cast<size_t>(kYorkStateLength) : state.size());
    out << "}";
    result = out.str();
    return true;
  }
  return false;
}

}  // namespace
