// Generated by worker/test/write-protocol-class-static-bridge.mjs.
// Do not edit by hand.

#include "ir_Airton.h"
#include "ir_Airwell.h"
#include "ir_Amcor.h"
#include "ir_Argo.h"
#include "ir_Bosch.h"
#include "ir_Carrier.h"
#include "ir_Coolix.h"
#include "ir_Corona.h"
#include "ir_Daikin.h"
#include "ir_Delonghi.h"
#include "ir_Ecoclim.h"
#include "ir_Electra.h"
#include "ir_Eurom.h"
#include "ir_Fujitsu.h"
#include "ir_Goodweather.h"
#include "ir_Gree.h"
#include "ir_Haier.h"
#include "ir_Hitachi.h"
#include "ir_Kelon.h"
#include "ir_Kelvinator.h"
#include "ir_LG.h"
#include "ir_Midea.h"
#include "ir_Mirage.h"
#include "ir_Mitsubishi.h"
#include "ir_MitsubishiHeavy.h"
#include "ir_Neoclima.h"
#include "ir_Panasonic.h"
#include "ir_Rhoss.h"
#include "ir_Samsung.h"
#include "ir_Sanyo.h"
#include "ir_Tcl.h"
#include "ir_Technibel.h"
#include "ir_Teco.h"
#include "ir_Toshiba.h"
#include "ir_Transcold.h"
#include "ir_Trotec.h"
#include "ir_Truma.h"
#include "ir_Vestel.h"
#include "ir_Voltas.h"
#include "ir_Whirlpool.h"
#include "ir_York.h"

namespace {

bool generateClassStaticJson(const char *className,
                             const std::vector<uint8_t> &state,
                             const char *methodName,
                             const char *argsCsv,
                             std::string &result) {
  if (className == nullptr || *className == '\0') {
    result = errorJson("className is required");
    return true;
  }
  if (methodName == nullptr || *methodName == '\0') {
    result = errorJson("method is required");
    return true;
  }
  const std::vector<uint64_t> args = parseWideNumbers(argsCsv);
  if (!std::strcmp(className, "IRAirtonAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRAirtonAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRAirtonAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRAirtonAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRAirtonAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRAirwellAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRAirwellAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRAirwellAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRAirwellAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRAirwellAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRAmcorAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRAmcorAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRAmcorAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRAmcorAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRAmcorAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRArgoAC")) {
    if (!std::strcmp(methodName, "getMessageType") && args.size() == 1) {
      if (state.empty()) {
        result = errorJson("IRArgoAC.getMessageType requires state bytes");
        return true;
      }
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRArgoAC\",";
      out << "\"method\":\"getMessageType\",";

      const long long value = static_cast<long long>(IRArgoAC::getMessageType(state.data(), static_cast<uint16_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "getStateLengthForIrMsgType") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRArgoAC\",";
      out << "\"method\":\"getStateLengthForIrMsgType\",";

      const long long value = static_cast<long long>(IRArgoAC::getStateLengthForIrMsgType(static_cast<argoIrMessageType_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRArgoAC_WREM3")) {
    if (!std::strcmp(methodName, "getMessageType") && args.size() == 0) {
      if (state.empty()) {
        result = errorJson("IRArgoAC_WREM3.getMessageType requires state bytes");
        return true;
      }
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRArgoAC_WREM3\",";
      out << "\"method\":\"getMessageType\",";
      ArgoProtocolWREM3 rawStruct0 = {};
      std::memcpy(rawStruct0.raw, state.data(), std::min(state.size(), sizeof(rawStruct0.raw)));
      const long long value = static_cast<long long>(IRArgoAC_WREM3::getMessageType(rawStruct0));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "getMessageType") && args.size() == 1) {
      if (state.empty()) {
        result = errorJson("IRArgoAC_WREM3.getMessageType requires state bytes");
        return true;
      }
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRArgoAC_WREM3\",";
      out << "\"method\":\"getMessageType\",";

      const long long value = static_cast<long long>(IRArgoAC_WREM3::getMessageType(state.data(), static_cast<uint16_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "getStateLengthForIrMsgType") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRArgoAC_WREM3\",";
      out << "\"method\":\"getStateLengthForIrMsgType\",";

      const long long value = static_cast<long long>(IRArgoAC_WREM3::getStateLengthForIrMsgType(static_cast<argoIrMessageType_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRBosch144AC")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRBosch144AC\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRBosch144AC::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRBosch144AC\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRBosch144AC::toCommonFanSpeed(static_cast<uint16_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRCarrierAc64")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRCarrierAc64\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRCarrierAc64::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRCarrierAc64\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRCarrierAc64::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRCoolixAC")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRCoolixAC\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRCoolixAC::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRCoolixAC\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRCoolixAC::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRCoronaAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRCoronaAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRCoronaAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRCoronaAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRCoronaAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRDaikin312")) {
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin312\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRDaikin312::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin312\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRDaikin312::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRDaikinESP")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikinESP\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRDaikinESP::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikinESP\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRDaikinESP::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRDaikin2")) {
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin2\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRDaikin2::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin2\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRDaikin2::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRDaikin160")) {
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin160\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRDaikin160::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRDaikin176")) {
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin176\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRDaikin176::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin176\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRDaikin176::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin176\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRDaikin176::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRDaikin128")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin128\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRDaikin128::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin128\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRDaikin128::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRDaikin64")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin64\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRDaikin64::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDaikin64\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRDaikin64::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRDelonghiAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDelonghiAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRDelonghiAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRDelonghiAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRDelonghiAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IREcoclimAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IREcoclimAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IREcoclimAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IREcoclimAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IREcoclimAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRElectraAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRElectraAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRElectraAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRElectraAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRElectraAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IREuromAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IREuromAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IREuromAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IREuromAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IREuromAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwing") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IREuromAc\",";
      out << "\"method\":\"toCommonSwing\",";

      const long long value = static_cast<long long>(IREuromAc::toCommonSwing(args[0] != 0));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRFujitsuAC")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRFujitsuAC\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRFujitsuAC::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRFujitsuAC\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRFujitsuAC::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRGoodweatherAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRGoodweatherAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRGoodweatherAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRGoodweatherAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRGoodweatherAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRGreeAC")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRGreeAC\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRGreeAC::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRGreeAC\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRGreeAC::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRGreeAC\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRGreeAC::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRGreeAC\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRGreeAC::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRHaierAC")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRHaierAC::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRHaierAC::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRHaierAC::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRHaierAC176")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC176\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRHaierAC176::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC176\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRHaierAC176::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC176\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRHaierAC176::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC176\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRHaierAC176::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRHaierAC160")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC160\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRHaierAC160::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC160\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRHaierAC160::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHaierAC160\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRHaierAC160::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHitachiAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRHitachiAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHitachiAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRHitachiAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc1")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHitachiAc1\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRHitachiAc1::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHitachiAc1\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRHitachiAc1::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc424")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHitachiAc424\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRHitachiAc424::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc344")) {
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHitachiAc344\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRHitachiAc344::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRHitachiAc296")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHitachiAc296\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRHitachiAc296::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRHitachiAc296\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRHitachiAc296::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRKelonAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRKelonAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRKelonAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRKelonAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRKelonAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRKelon168Ac")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRKelon168Ac\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRKelon168Ac::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRKelon168Ac\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRKelon168Ac::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRKelvinatorAC")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRKelvinatorAC\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRKelvinatorAC::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRKelvinatorAC\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRKelvinatorAC::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRLgAc")) {
    if (!std::strcmp(methodName, "getVaneCode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRLgAc\",";
      out << "\"method\":\"getVaneCode\",";

      const long long value = static_cast<long long>(IRLgAc::getVaneCode(static_cast<uint32_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRLgAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRLgAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRLgAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRLgAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRLgAc\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRLgAc::toCommonSwingV(static_cast<uint32_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonVaneSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRLgAc\",";
      out << "\"method\":\"toCommonVaneSwingV\",";

      const long long value = static_cast<long long>(IRLgAc::toCommonVaneSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRMideaAC")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMideaAC\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRMideaAC::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMideaAC\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRMideaAC::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRMirageAc")) {
    if (!std::strcmp(methodName, "getModel") && args.size() == 0) {
      if (state.empty()) {
        result = errorJson("IRMirageAc.getModel requires state bytes");
        return true;
      }
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMirageAc\",";
      out << "\"method\":\"getModel\",";

      const long long value = static_cast<long long>(IRMirageAc::getModel(state.data()));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMirageAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRMirageAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 2) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMirageAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRMirageAc::toCommonFanSpeed(static_cast<uint8_t>(args[0]), static_cast<mirage_ac_remote_model_t>(args[1])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMirageAc\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRMirageAc::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishiAC")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiAC\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRMitsubishiAC::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiAC\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRMitsubishiAC::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiAC\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRMitsubishiAC::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiAC\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRMitsubishiAC::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishi136")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishi136\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRMitsubishi136::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishi136\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRMitsubishi136::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishi136\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRMitsubishi136::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishi112")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishi112\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRMitsubishi112::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishi112\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRMitsubishi112::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishi112\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRMitsubishi112::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishi112\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRMitsubishi112::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishiHeavy152Ac")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiHeavy152Ac\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRMitsubishiHeavy152Ac::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiHeavy152Ac\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRMitsubishiHeavy152Ac::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiHeavy152Ac\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRMitsubishiHeavy152Ac::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiHeavy152Ac\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRMitsubishiHeavy152Ac::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRMitsubishiHeavy88Ac")) {
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiHeavy88Ac\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRMitsubishiHeavy88Ac::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiHeavy88Ac\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRMitsubishiHeavy88Ac::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRMitsubishiHeavy88Ac\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRMitsubishiHeavy88Ac::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRNeoclimaAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRNeoclimaAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRNeoclimaAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRNeoclimaAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRNeoclimaAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRPanasonicAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRPanasonicAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRPanasonicAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRPanasonicAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRPanasonicAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRPanasonicAc\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRPanasonicAc::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingH") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRPanasonicAc\",";
      out << "\"method\":\"toCommonSwingH\",";

      const long long value = static_cast<long long>(IRPanasonicAc::toCommonSwingH(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRPanasonicAc32")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRPanasonicAc32\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRPanasonicAc32::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRPanasonicAc32\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRPanasonicAc32::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRPanasonicAc32\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRPanasonicAc32::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRRhossAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRRhossAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRRhossAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRRhossAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRRhossAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRSamsungAc")) {
    if (!std::strcmp(methodName, "getSectionChecksum") && args.size() == 0) {
      if (state.empty()) {
        result = errorJson("IRSamsungAc.getSectionChecksum requires state bytes");
        return true;
      }
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRSamsungAc\",";
      out << "\"method\":\"getSectionChecksum\",";

      const long long value = static_cast<long long>(IRSamsungAc::getSectionChecksum(state.data()));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRSamsungAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRSamsungAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRSamsungAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRSamsungAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRSanyoAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRSanyoAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRSanyoAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRSanyoAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRSanyoAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRSanyoAc\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRSanyoAc::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRSanyoAc88")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRSanyoAc88\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRSanyoAc88::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRSanyoAc88\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRSanyoAc88::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRTcl112Ac")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTcl112Ac\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRTcl112Ac::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTcl112Ac\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRTcl112Ac::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonSwingV") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTcl112Ac\",";
      out << "\"method\":\"toCommonSwingV\",";

      const long long value = static_cast<long long>(IRTcl112Ac::toCommonSwingV(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRTechnibelAc")) {
    if (!std::strcmp(methodName, "toCommonSwing") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTechnibelAc\",";
      out << "\"method\":\"toCommonSwing\",";

      const long long value = static_cast<long long>(IRTechnibelAc::toCommonSwing(args[0] != 0));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTechnibelAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRTechnibelAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTechnibelAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRTechnibelAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRTecoAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTecoAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRTecoAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTecoAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRTecoAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRToshibaAC")) {
    if (!std::strcmp(methodName, "getInternalStateLength") && args.size() == 1) {
      if (state.empty()) {
        result = errorJson("IRToshibaAC.getInternalStateLength requires state bytes");
        return true;
      }
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRToshibaAC\",";
      out << "\"method\":\"getInternalStateLength\",";

      const long long value = static_cast<long long>(IRToshibaAC::getInternalStateLength(state.data(), static_cast<uint16_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRToshibaAC\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRToshibaAC::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRToshibaAC\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRToshibaAC::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRTranscoldAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTranscoldAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRTranscoldAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTranscoldAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRTranscoldAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRTrotecESP")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTrotecESP\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRTrotecESP::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTrotecESP\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRTrotecESP::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRTrotec3550")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTrotec3550\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRTrotec3550::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTrotec3550\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRTrotec3550::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRTrumaAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTrumaAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRTrumaAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRTrumaAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRTrumaAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRVestelAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRVestelAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRVestelAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRVestelAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRVestelAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRVoltas")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRVoltas\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRVoltas::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRVoltas\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRVoltas::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRWhirlpoolAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRWhirlpoolAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRWhirlpoolAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRWhirlpoolAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRWhirlpoolAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  if (!std::strcmp(className, "IRYorkAc")) {
    if (!std::strcmp(methodName, "toCommonMode") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRYorkAc\",";
      out << "\"method\":\"toCommonMode\",";

      const long long value = static_cast<long long>(IRYorkAc::toCommonMode(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    if (!std::strcmp(methodName, "toCommonFanSpeed") && args.size() == 1) {
      (void)state;
      std::ostringstream out;
      out << "{\"kind\":\"classStatic\",";
      out << "\"className\":\"IRYorkAc\",";
      out << "\"method\":\"toCommonFanSpeed\",";

      const long long value = static_cast<long long>(IRYorkAc::toCommonFanSpeed(static_cast<uint8_t>(args[0])));
      out << "\"result\":" << value;
      out << "}";
      result = out.str();
      return true;
    }
    result = errorJson("unsupported protocol class static method");
    return true;
  }
  return false;
}

}  // namespace
